version: "3.0"
services:
  restapp:
    image: amarps-restapp
    build: src/restService/
    ports:
      - "80:80"

  grpcapp:
    image: amarps-grpcapp
    build: src/grpcService/
    ports:
      - "80:80"
  
  mongodb:
    image: mongo:4.4.3
    ports:
      - "6379:6379"
